package routes

import (
	nethttp "net/http"

	"github.com/goravel/framework/contracts/http"

	"goravel/app/facades"
	"goravel/docs"
)

// swaggerUIHTML is a minimal Swagger UI page that loads the OpenAPI spec from
// /swagger/doc.json. The assets (JS/CSS) are loaded from a public CDN so we
// don't need to bundle swagger-ui-dist locally.
const swaggerUIHTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Tesmajoo API (Goravel) — Swagger UI</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
    <style>
      body { margin: 0; }
    </style>
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
    <script>
      window.onload = function () {
        window.ui = SwaggerUIBundle({
          url: "/swagger/doc.json",
          dom_id: "#swagger-ui",
          deepLinking: true,
          presets: [SwaggerUIBundle.presets.apis],
          layout: "BaseLayout",
        });
      };
    </script>
  </body>
</html>`

// Swagger registers the Swagger UI and the generated OpenAPI JSON endpoint.
//
// Routes:
//
//	GET /swagger           → Swagger UI (HTML)
//	GET /swagger/          → Swagger UI (HTML, trailing slash)
//	GET /swagger/*any      → Swagger UI (HTML, sub-paths)
//	GET /swagger/doc.json  → OpenAPI 2.0 spec (generated by swag)
func Swagger() {
	facades.Route().Get("/swagger", swaggerUIHandler)
	facades.Route().Get("/swagger/doc.json", swaggerDocHandler)
}

// swaggerUIHandler serves the Swagger UI HTML.
func swaggerUIHandler(ctx http.Context) http.Response {
	return ctx.Response().
		Header("Content-Type", "text/html; charset=utf-8").
		String(nethttp.StatusOK, swaggerUIHTML)
}

// swaggerDocHandler serves the generated OpenAPI JSON spec.
func swaggerDocHandler(ctx http.Context) http.Response {
	return ctx.Response().
		Header("Content-Type", "application/json; charset=utf-8").
		String(nethttp.StatusOK, docs.SwaggerInfo.ReadDoc())
}
